language: node_js
services:
  - mongodb
  - redis-server
node_js:
  - '8'
addons:
  sonarcloud:
    organization: "rifhice-github"
env:
  - FOLDER=client
  - FOLDER=api
  - FOLDER=hub
script: 
  - npm install --prefix $FOLDER && npm run test --prefix $FOLDER
  - cd $FOLDER && sonar-scanner