export default actions = {
    "FETCHED_DEVICE_USERS": "FETCHED_DEVICE_USERS",
    "UPDATE_USER_RANK": "UPDATE_USER_RANK",
    "ADD_USER_TO_DEVICE": "ADD_USER_TO_DEVICE",
    "REMOVE_USER_TO_DEVICE": "REMOVE_USER_TO_DEVICE",
    "ADD_RESTRICTION_TO_USER": "ADD_RESTRICTION_TO_USER",
    "REMOVE_RESTRICTION_TO_USER": "REMOVE_RESTRICTION_TO_USER"
}