export default actions = {
    "FETCHED_SENSOR": "FETCHED_SENSORS",
    "REGISTERED_SENSOR": "REGISTERED_SENSOR",
    "UPDATE_SENSOR_ISCONNECTED": "UPDATE_SENSOR_ISCONNECTED",
    "UPDATE_ENVIRONMENT_VARIABLE_VALUE": "UPDATE_ENVIRONMENT_VARIABLE_VALUE"
}