export default actions = {
    "SAVE_TOKEN": "SAVE_TOKEN",
    "REMOVE_TOKEN": "REMOVE_TOKEN",
    "USER_INFORMATION": "USER_INFORMATION",
    "LOGOUT": "LOGOUT",
    "NEW_DEVICE_PAIRED": "NEW_DEVICE_PAIRED",
    "FAVOURITE_ACTUATOR": "FAVOURITE_ACTUATOR",
    "FAVOURITE_SENSOR": "FAVOURITE_SENSOR",
    "UNFAVOURITE": "UNFAVOURITE",
    "FETCHED_FAVOURITE": "FETCHED_FAVOURITE",
}